//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestMVCApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class GOODS
    {
        public int id { get; set; }
        public string description { get; set; }
        public Nullable<double> quantity { get; set; }
        public string unit { get; set; }
        public Nullable<double> price { get; set; }
        public System.DateTime creation_date { get; set; }
    }
}
